# Flex
neofetch --ascii_distro macos_small --disable theme memory icons resolution cpu gpu uptime host --color_blocks
## History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=32768; # Larger bash history (allow 32³ entries; default is 500)
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000
HISTCONTROL=ignoredups;
HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"; # Make some commands not show up in history

CASE_SENSITIVE="true"
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"
# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"
COMPLETION_WAITING_DOTS="true"
# Dotfiles location
DOTFILES="$HOME/dotfiles"

# Config
autoload -U compinit && compinit -u
source $DOTFILES/zsh/config/theme-and-appearance.zsh
source $DOTFILES/zsh/config/completion.zsh
source $DOTFILES/zsh/config/git.zsh
source $DOTFILES/zsh/config/key-bindings.zsh

# Theme
source $DOTFILES/zsh/themes/robbyrussel.zsh-theme

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh


# Custom sources
for file in $DOTFILES/zsh/sourced/*; do
   source "$file"
done

export TERMINAL=/usr/local/bin/st
export EDITOR=/usr/bin/nvim

# Path config
export PATH="$DOTFILES/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
alias luamake=/home/kelvin/.config/lua-language-server/3rd/luamake/luamake
